### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by yphanikumar1995** [kokuwaio/helm-charts#105]
**Describe the bug**

**Version of Helm and Kubernetes**:

Helm Version:

```console
v3.3.4
```

Kubernetes Version:

```console
Server Version: v1.21.7
```

**Which version of the chart**: 13.2.0

**What happened**:

Memory usage is keep on increasing and getting restart when it reached the limit

**What you expected to happen**:

Should not be increase 

**How to reproduce it** (as minimally and precisely as possible):

<~--
This could be something like:

values.yaml (only put values which differ from the defaults)

```
resources:
   limits:
     cpu: 1000m
     memory: 500Mi
   requests:
     cpu: 100m
     memory: 200Mi
env:
  RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR: 0.9

elasticsearch:
  auth:
    enabled: true
    user: "user"
    password: "password"
  hosts: ["es-master.default:9200"]
  scheme: "https"
  sslVerify: false
  requestTimeout: "10s"
  logLevel: "info"
  suppressTypeName: true



configMaps:
  useDefaults:
    kubernetesMetadataFilterConfig:
       watch: false

extraConfigMaps:
  containers.site.conf: |-
    # ignore containers labeled app_kubernetes_io/name: "fluentd-elasticsearch"
    <filter kubernetes.**>
    @type grep
    <exclude>
        key $.kubernetes.labels.app_kubernetes_io/name
        pattern fluentd-elasticsearch
    </exclude>
    </filter>

```

```
helm upgrade --namespace default --install fluentd kokuwa/fluentd-elasticsearch -f values.yaml --version 13.2.0
```

-->

**Anything else we need to know**:

<img width="1783" alt="Screenshot 2022-03-08 at 10 38 18 AM" src="https://user-images.githubusercontent.com/81069965/157170895-8880e755-4eac-40c3-a8cf-91f5bf1b041c.png">
