### ISSUE TITLE
[Question] Is ILM support now fully functional?

### ISSUE THREAD

**Issue by alhails** [kokuwaio/helm-charts#17]
Hi,

I've been trying to get ILM support working, but so far no good.  No errors, but my indexes aren't being linked to an ILM policy, and no ILM policy is created.

I was tracking this issue in the old repo - https://github.com/kiwigrid/helm-charts/issues/396
but also noticed that there have been some recent commits in this area e.g. a6b48b69658a5e1e94a3531d8205002e5ce8142c

For info I'm using 
* fluentd-elasticsearch 10.2.0
* elasticsearch 7.8

Thanks

Alastair

**Comment by monotek** [comment]
The commit your referencing hast to do with: https://github.com/kokuwaio/helm-charts/issues/13

So yes, regarding to the ticket above it works.

**Comment by alhails** [comment]
Ok, but the author of #13 seems to have a different fluent.conf than the one that is provisioned via the configmaps in your chart.  They were also using a separate docker image to the one you are pointing at (quay.io/fluentd_elasticsearch/fluentd)

I'm not sure whether either of these things are important, but with regard to the different fluent.conf...
The difference I noticed was that the author was supplying a template name.  The documentation at https://github.com/uken/fluent-plugin-elasticsearch#enable-index-lifecycle-management seemed to suggest that this is a requirement for ILM?

If this is the case, should this be added to your configmap?

Apologies if I'm missing something obvious here, but I'm no elasticsearch expert.

**Comment by monotek** [comment]
The ilm stuff is disabled by default so thats the reason theres nothing in the config.
You have to fill out the stuff yourself.

I've fixed the ilm policy to work as described in the readme thoug: https://github.com/kokuwaio/helm-charts/pull/19

**Comment by alhails** [comment]
Don't think we're talking about the same thing.  I was referring to the generated fluent.conf that is written to the container (via the configmap).

For reference though, my ilm config looks like this...

```
    ilm:
      enabled: true
      policy_id: logstash-policy
      policy:
        policy:
          phases:
            hot:
              actions:
                rollover:
                  max_size: "50gb"
                  max_age: "1d"
                set_priority:
                  priority: 100
            delete:
              min_age: 120d
              actions:
                delete: {}
```

(PS I will remove the extra policy as you suggested once you have merged your change)

Anyway I've yet to see any results in terms of new ILM policies in elasticsearch.  I don't seem to get any obvious errors logged by fluentd or even any sign that it might be trying to create the policy.

When I saw that the author on #13 had also supplied template_name in the fluent.conf, I did a bit more research and found mention of it in the plugin documentation (https://github.com/uken/fluent-plugin-elasticsearch#enable-index-lifecycle-management).  So at the moment, I'm not sure whether this is what is stopping it working or not.

I'm continuing to read more into elasticsearch, but at the moment it's very slow going.

Thanks, I appreciate your help
