### ISSUE TITLE
Mismatch between PrometheusRules queries and exported "job" metric label

### ISSUE THREAD

**Issue by Ghazgkull** [kokuwaio/helm-charts#86]
There's a mismatch between some of the rules in the PrometheusRule CRD included in this helm chart and the actual metrics exported by fluent, which results in some rules not working.

**Describe the bug**

The issue is that the queries reference two different "job" labels. For example:

FluentdNodeDown queries the "up" metric using the label `job="myrelease-fluentd-elasticsearch"`. This will *never* fire because the "up" metric exposed by fluentd's `job` label is actually just `myrelease`.
```
    - alert: FluentdNodeDown
      annotations:
        description: Prometheus could not scrape {{ $labels.job }} for more than 10
          minutes
        summary: fluentd cannot be scraped
      expr: up{job="myrelease-fluentd-elasticsearch"} == 0
      for: 10m
      labels:
        service: fluentd
        severity: warning
```

Meanwhile FluentdRecordsCountsHigh queries the `fluentd_output_status_emit_records` metric using `job="myrelease"`. This *does* match what the metric actually looks like coming from fluentd:
```
    - alert: FluentdRecordsCountsHigh
      annotations:
        description: In the last 5m, records counts increased 3 times, comparing to
          the latest 15 min.
        summary: fluentd records count are critical
      expr: |
        sum(rate(fluentd_output_status_emit_records{job="dam"}[5m])) BY (instance) >  (3 * sum(rate(fluentd_output_status_emit_records{job="dam"}[15m])) BY (instance))
      for: 1m
      labels:
        service: fluentd
        severity: critical
```

This mismatch is clearly wrong, but I'm not sure what the right fix should be. We could either:
A) Fix the value of the metric coming from fluentd so that the `job` label's value is `myrelease-fluentd-elasticsearch` and then update rules like FluentdRecordsCountsHigh to match OR...
B) Fix the FluentdNodeDown rule's query to look for the label value that actually matches what comes from fluentd, in this case `myrelease`.

I think option A is actually better. The `job` label coming from fluentd should be `myrelease-fluentd-elasticsearch`, not just `myrelease`. The same release name is often used for multiple helm charts which would lead to conflicts.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"dirty", GoVersion:"go1.16.4"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
11.13.0

**What happened**:
The `FluentdNodeDown` alert doesn't work because the job label it queries doesn't match what comes from fluentd.

Also, the job label which comes from the fluentd pod is "bad" in that it is just the helm release name. The label value that the `FluentdNodeDown` rule references is actually better.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

Deploy the chart with
prometheusRule.enabled=true
serviceMonitor.enabled=true

**Anything else we need to know**:

I'd be happy to put together a PR. I could easily update the PrometheusRule, but I'm not sure how to update the value of the `job` label which comes from the metrics. If someone (@monotek ?) could give me a pointer, I can fix it.
